# Generated by Django 4.1.5 on 2023-07-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='post_type',
            field=models.CharField(choices=[('O', 'Одиночная фотосессия'), ('G', 'Групповая фотосессия'), ('Т', 'Тематическая съёмка'), ('Б', 'Фото без обработки'), ('О', 'Обработка фото'), ('В', 'Видеосъёмка')], max_length=1, null=True),
        ),
    ]
