# Generated by Django 4.1.5 on 2023-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0005_alter_author_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlename', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
