# Generated by Django 4.1.5 on 2023-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0006_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='titlename',
            field=models.EmailField(max_length=150),
        ),
    ]
