# Generated by Django 4.1.5 on 2023-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0007_alter_qa_titlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='titlename',
            field=models.EmailField(max_length=254),
        ),
    ]
