# Generated by Django 4.1.5 on 2023-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0008_alter_qa_titlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='time02',
            field=models.CharField(default='12:00 - 13:00', max_length=11, null=True),
        ),
    ]
