# Generated by Django 4.1.5 on 2023-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphoto', '0010_alter_author_time02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data',
            field=models.CharField(default='01/01/24', max_length=10, null=True),
        ),
    ]
